version: '3'

services:
  app:
    image: app
    restart: always
    build: ./
    volumes:
      - ./:/var/www/app
    working_dir: /var/www/app
    ports:
      - 3000:3000
    environment:
      DB_HOST: host.docker.internal
    command: sh -c 'npm i && npm run start:dev'
    networks:
      otus-net:
  db:
    container_name: db
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
networks:
  otus-net:
